package p2;

public class Solution {

	/**
	 * Each new term in the Fibonacci sequence is generated by adding the
	 * previous two terms. By starting with 1 and 2, the first 10 terms will be:
	 * 
	 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 * 
	 * By considering the terms in the Fibonacci sequence whose values do not
	 * exceed four million, find the sum of the even-valued terms.
	 * 
	 * @param args
	 */
	public static void main(String[] args) {
		int sum = 0;
		int pre = 1;
		int next = 1;
		int tmp = 0;
		while (next < 4000000) {
			if (next % 2 == 0) {
				sum += next;
			}
			tmp = pre;
			pre = next;
			next = tmp + next;
		}
		System.out.println(sum);
	}
}
